version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py create_admin &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=imaginarium
      - POSTGRES_PASSWORD=imaginarium
      - POSTGRES_DB=imaginarium_dev

  redis:
    image: redis:7.0-alpine

  celery:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery -A imaginarium worker -l info
    volumes:
      - ./:/usr/src
    env_file:
      - ./docker/.env.dev
    depends_on:
      - redis

  celery-beat:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: celery -A imaginarium beat -l info
    volumes:
      - ./:/usr/src
    env_file:
      - ./docker/.env.dev
    depends_on:
      - redis

volumes:
  postgres_data: