version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: ./start-web.prod.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./docker/.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/.env.prod.db

  nginx:
    build: ./docker/nginx
    ports: 
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web

  redis:
    image: redis:7.0-alpine

  celery:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: ./start-celery.prod.sh
    env_file:
      - ./docker/.env.prod
    depends_on:
      - redis

  celery-beat:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: ./start-celery-beat.prod.sh
    env_file:
      - ./docker/.env.prod
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: